// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPgAOaU4NFS1ZSVP-H95IpkobkZFiHjGM',
    appId: '1:1034745202099:web:ef1c5a76d5d40c462df7c6',
    messagingSenderId: '1034745202099',
    projectId: 'easyexam-da571',
    authDomain: 'easyexam-da571.firebaseapp.com',
    storageBucket: 'easyexam-da571.appspot.com',
    measurementId: 'G-NMB5KZ69Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTboUcaK93tRCXPHSc9nqDwG0EQaVaPro',
    appId: '1:1034745202099:android:29e956afbaadff1b2df7c6',
    messagingSenderId: '1034745202099',
    projectId: 'easyexam-da571',
    storageBucket: 'easyexam-da571.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9V7hUWuKRz99CAnaQp7FM0XP2miqgPn0',
    appId: '1:1034745202099:ios:f1167f532847f5912df7c6',
    messagingSenderId: '1034745202099',
    projectId: 'easyexam-da571',
    storageBucket: 'easyexam-da571.appspot.com',
    iosBundleId: 'io.initappz.flutter.exam.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9V7hUWuKRz99CAnaQp7FM0XP2miqgPn0',
    appId: '1:1034745202099:ios:f3c5766d3666c7bd2df7c6',
    messagingSenderId: '1034745202099',
    projectId: 'easyexam-da571',
    storageBucket: 'easyexam-da571.appspot.com',
    iosBundleId: 'io.initappz.flutter.exam.user.RunnerTests',
  );
}
